name: Deploy to Firebase

on:
    # Deploy on push to main...
    push:
        branches: [main]

    # ...or manually.
    workflow_dispatch:

jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Install Python
              uses: actions/setup-python@v5
              with:
                  python-version: "3.12"

            - name: Install Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: 20

            - name: Install Firebase CLI
              uses: w9jds/setup-firebase@main
              with:
                  tools-version: 13.22.1
                  gcp_sa_key: ${{ secrets.GCP_SA_KEY }}
                  project_id: roanluder
                  project_path: ./backend

            - name: Deploy to Firebase
              run: |
                  python -m venv backend/functions/venv
                  source backend/functions/venv/bin/activate
                  pip install -r backend/functions/requirements.txt
                  firebase deploy
